title: [Priscila Campos]
description: [ Sobre m铆
Soy nutricionista con un enfoque anal铆tico y t茅cnico. Mi experiencia en el sector salud me llev贸 a descubrir el valor de los datos para mejorar procesos, generar estrategias y aportar soluciones basadas en evidencia.
 Actualmente finalic茅 mi formaci贸n como Analista de Datos en el bootcamp de TripleTen, donde trabaj茅 con herramientas como Python, SQL y Tableau, aplic谩ndolas a proyectos de an谩lisis estad铆stico, segmentaci贸n de usuarios y embudos de conversi贸n.
 Me entusiasma traducir informaci贸n compleja en hallazgos claros y accionables, integrando la l贸gica de programaci贸n con la comprensi贸n del comportamiento humano. He desarrollado proyectos que conectan con el mundo del an谩lisis de datos.]
logo: 
show_downloads: true
remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme 
