title: [Priscila Campos]
description: [ğŸ‘‹ğŸ¼Â¡Hola! AquÃ­ encontrarÃ¡s proyectos de AnÃ¡lisis de Datos pensados para transformar informaciÃ³n en decisiones con impacto. ğŸš€ğŸ“ˆ]
logo: /images/perfil.png
remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme 
